servers:
  server1:
    host: "192.168.1.2"
    bind: "2000/tcp, 2001-2256/udp"

  server2:
    host: "192.168.1.3"
    ports:
      - from: 3000
        to: 3100
        isrange: true
        protocol: "tcp"

      - from: 4000
        to: 4200
        isrange: true
        protocol: "udp"
